openapi: 3.0.0

info:
  version: '1.0'
  title: 'LBAW GameSpace Web API'
  description: 'Web Resources Specification (A7) for GameSpace'

servers:
  - url: http://lbaw.fe.up.pt
    description: Production server

externalDocs:
 description: Find more info here.
 url: https://web.fe.up.pt/~ssn/wiki/teach/lbaw/medialib/a07

tags:
  - name: 'M01: Authentication and Individual Profile'
  - name: 'M02: Products'
  - name: 'M03: Reviews and Wishlist'
  - name: 'M04: Cart'
  - name: 'M05: Static Pages'
  - name: 'MO06: Management Area'
